@echo off
echo Starting Streamlit Real-Time Vehicle Detection...
call venv\Scripts\activate.bat 2>nul || echo Virtual environment not found, proceeding with global Python...
streamlit run app.py
pause
